spring:
  application:
    name: FoodDelivery

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true
    hibernate:
      ddl-auto: update
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_SECRET}
            scope:
              - openid
              - profile
              - email
            redirect-uri: http://localhost:5173/login/oauth2/code/google
            authorization-grant-type: authorization_code
        provider:
          google:
            user-info-uri: https://www.googleapis.com/oauth2/v2/userinfo
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${SPRING_MAIL_USERNAME}
    password: ${SPRING_MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            require: true

support:
  email: penaldo2005vg@gmail.com

app:
  frontend:
    url: ${FRONTEND_URL}

jwt:
  secretKey: ${JWT_SECRET_KEY}
  accessTokenExpiration: 900
  refreshTokenExpiration: 604800000

stripe:
  api:
    key: ${STRIPE_API_KEY}
  webhook:
    secret: ${STRIPE_WEBHOOK_SECRET}

vnPay:
  tmnCode: ${VNPAY_TMN_CODE}
  hashSecret: ${VNPAY_HASH_SECRET}
  payUrl: ${VNPAY_PAY_URL}
  returnUrl: ${VNPAY_RETURN_URL}
  command: ${VNPAY_COMMAND}
  version: ${VNPAY_VERSION}
  orderType: ${VNPAY_ORDER_TYPE}

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
